{% set name = "azure-ai-ml" %}
{% set version = "1.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-ai-ml-{{ version }}.tar.gz
  sha256: 5799f47366edc40f2ffac8ed5fdff3899b453f3a20dcbc2f7634e976e7cbafda

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - pip
  run:
    - python >=3.7,<4.0
    - pyyaml <7.0.0,>=5.1.0
    - msrest >=0.6.18
    - azure-core <2.0.0,>=1.23.0
    - azure-mgmt-core <2.0.0,>=1.3.0
    - marshmallow <4.0.0,>=3.5
    - jsonschema <5.0.0,>=4.0.0
    - tqdm <5.0.0
    - strictyaml <2.0.0
    - colorama <0.5.0
    - pyjwt <3.0.0
    - azure-storage-blob <13.0.0,>=12.10.0
    - azure-storage-file-share <13.0.0
    - azure-storage-file-datalake <13.0.0
    - pydash <7.0.6,>=6.0.0
    - isodate
    - azure-common <2.0.0,>=1.1
    - typing-extensions <5.0.0
    - opencensus-ext-azure <2.0.0
#azure-ai-ml 1.16.0 requires opencensus-ext-logging, which is not installed.
    #- opencensus-ext-logging

test:
  imports:
    - azure.ai.ml
    - azure.ai.ml._arm_deployments
  commands:
    #- pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Machine Learning Client Library for Python
  dev_url: https://github.com/Azure/azure-sdk-python
  license: Apache-2.0
  license_file: NOTICE.txt

extra:
  recipe-maintainers:
    - rxm7706
