# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: azure-ai-ml
  version: "1.29.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure_ai_ml-${{ version }}.tar.gz
  sha256: 052c6bc14a986b3ac3610ca59d24a0393fc09635dfb57e6506c3159c10039144

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - pyyaml >=5.1.0,<7.0.0
    - msrest >=0.6.18,<1.0.0
    - azure-core >=1.23.0
    - azure-mgmt-core >=1.3.0
    - marshmallow >=3.5,<4.0.0
    - jsonschema >=4.0.0,<5.0.0
    - tqdm <5.0.0
    - strictyaml <2.0.0
    - colorama <1.0.0
    - pyjwt <3.0.0
    - azure-storage-blob >=12.10.0
    - azure-storage-file-share
    - azure-storage-file-datalake >=12.2.0
    - pydash >=6.0.0,<9.0.0
    - isodate <1.0.0
    - azure-common >=1.1
    - typing_extensions <5.0.0
    - azure-monitor-opentelemetry
    - six >=1.11.0

tests:
  - python:
      imports:
        - azure.ai.ml
        - azure.ai.ml._arm_deployments
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Microsoft Azure Machine Learning Client Library for Python
  homepage: https://github.com/Azure/azure-sdk-for-python
  description: |
    Microsoft Azure Azure Core OpenTelemetry plugin Library for Python.
  repository: https://github.com/Azure/azure-sdk-for-python
  documentation: https://github.com/Azure/azure-sdk-for-python/blob/main/README.md
  license: Apache-2.0
  license_file: NOTICE.txt

extra:
  recipe-maintainers:
    - rxm7706
