# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.35.0"

package:
  name: azure-ai-ml
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/azure-ai-ml/azure_ai_ml-${{ version }}.tar.gz
  sha256: 280dd4cbcfe8a72d210731f5a3a3b34d70cedcb85b6111b42f7b1c9d6758f4e1

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - pyyaml >=5.1.0,<7.0.0
    - azure-core >=1.23.0
    - azure-mgmt-core >=1.3.0
    - marshmallow >=3.5,<4.0.0
    - jsonschema >=4.0.0,<5.0.0
    - tqdm <5.0.0
    - strictyaml <2.0.0
    - colorama <1.0.0
    - pyjwt <3.0.0
    - azure-storage-blob >=12.10.0
    - azure-storage-file-share
    - azure-storage-file-datalake >=12.2.0
    - pydash >=6.0.0,<9.0.0
    - isodate <1.0.0
    - typing_extensions <5.0.0
    - azure-monitor-opentelemetry

tests:
  - python:
      imports:
        - azure
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://pypi.org/project/azure-ai-ml/
  license: MIT
  license_file:
    - NOTICE.txt
    - LICENSE
  summary: Microsoft Azure Machine Learning Client Library for Python
  description: "Microsoft Azure Azure Core OpenTelemetry plugin Library for Python.\n"
  repository: https://github.com/Azure/azure-sdk-for-python
  documentation: https://github.com/Azure/azure-sdk-for-python/blob/main/README.md
extra:
  recipe-maintainers:
    - rxm7706
